services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: userver-base

  auth:
    build:
      context: ./auth-service
    depends_on:
      - base

  users:
    build:
      context: ./user-service
    depends_on:
      - base

  chat:
    build:
      context: ./chat-service
    depends_on:
      - base

  wall:
    build:
      context: ./wall-service
    depends_on:
      - base