components_manager:
    task_processors:
        main-task-processor:
            worker_threads: 2

        fs-task-processor:
            worker_threads: 2

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: 8082
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: info
                    overflow_behavior: discard

        dynamic-config:
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000

        testsuite-support: {}

        congestion-control:

        dns-client:
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: false
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor

        handler-users:
            path: /users
            method: GET,POST
            task_processor: main-task-processor